name: youtubeDownloader
description: A port in dart of the youtube. 



environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  html: ^0.14.0+3
  http: ^0.12.0+4
  dio: ^3.0.10

dev_dependencies:
  effective_dart: ^1.2.1
  dart_console: ^0.5.0